"""Rebuild database from scratch

Revision ID: 2c2817dbb630
Revises: 
Create Date: 2025-09-30 09:23:40.487076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2817dbb630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('chinese_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_accounts_chinese_name'), ['chinese_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_accounts_username'), ['username'], unique=True)

    op.create_table('system_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platform_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('chinese_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_users_chinese_name'), ['chinese_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_users_username'), ['username'], unique=True)

    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('system_number', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('computer_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_domain_joined', sa.Boolean(), nullable=True),
    sa.Column('is_workstation_domain_joined', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('warning_days', sa.Integer(), nullable=False),
    sa.Column('check_frequency_days', sa.Integer(), nullable=True),
    sa.Column('last_check_date', sa.Date(), nullable=True),
    sa.Column('next_check_date', sa.Date(), nullable=True),
    sa.Column('needs_qa_check', sa.Boolean(), nullable=False),
    sa.Column('qa_last_check_date', sa.Date(), nullable=True),
    sa.Column('qa_check_frequency_days', sa.Integer(), nullable=True),
    sa.Column('qa_next_check_date', sa.Date(), nullable=True),
    sa.Column('backup_method', sa.String(length=50), nullable=True),
    sa.Column('backup_frequency', sa.String(length=50), nullable=True),
    sa.Column('is_restore_verified', sa.Boolean(), nullable=True),
    sa.Column('last_restore_verification_date', sa.Date(), nullable=True),
    sa.Column('restore_verification_cycle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_needs_qa_check'), ['needs_qa_check'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_system_number'), ['system_number'], unique=True)

    op.create_table('check_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('checked_by', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_to_delete_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_to_delete_id'], ['system_accounts.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)

    op.create_table('role_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('current_role', sa.String(length=100), nullable=False),
    sa.Column('new_role', sa.String(length=100), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['system_accounts.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_change_requests_status'), ['status'], unique=False)

    op.create_table('system_user_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('system_role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['system_accounts.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('chinese_name', sa.String(length=64), nullable=False),
    sa.Column('computer_role', sa.String(length=100), nullable=True),
    sa.Column('workstation_role', sa.String(length=100), nullable=True),
    sa.Column('target_systems', sa.Text(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_requests_status'), ['status'], unique=False)

    op.create_table('workstation_user_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['system_accounts.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['system_role.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workstation_user_link')
    with op.batch_alter_table('user_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_requests_status'))

    op.drop_table('user_requests')
    op.drop_table('system_user_link')
    with op.batch_alter_table('role_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_change_requests_status'))

    op.drop_table('role_change_requests')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status'))

    op.drop_table('job')
    op.drop_table('deletion_requests')
    op.drop_table('check_history')
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_system_number'))
        batch_op.drop_index(batch_op.f('ix_system_needs_qa_check'))

    op.drop_table('system')
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_users_username'))
        batch_op.drop_index(batch_op.f('ix_platform_users_chinese_name'))

    op.drop_table('platform_users')
    op.drop_table('system_role')
    with op.batch_alter_table('system_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_system_accounts_chinese_name'))

    op.drop_table('system_accounts')
    op.drop_table('script')
    op.drop_table('group')
    # ### end Alembic commands ###
