"""Add it_check_content to System model

Revision ID: 7266a451fc61
Revises: 8cb06254020c
Create Date: 2025-10-23 10:09:39.058967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7266a451fc61'
down_revision = '8cb06254020c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('it_check_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('it_check_content')

    # ### end Alembic commands ###
