"""Add menjin deletion request model

Revision ID: 75783729cded
Revises: 2c2817dbb630
Create Date: 2025-10-13 12:58:23.067616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75783729cded'
down_revision = '2c2817dbb630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menjin_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('consumer_no', sa.String(length=64), nullable=False),
    sa.Column('consumer_name', sa.String(length=64), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menjin_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menjin_deletion_requests_consumer_no'), ['consumer_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_menjin_deletion_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menjin_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menjin_deletion_requests_status'))
        batch_op.drop_index(batch_op.f('ix_menjin_deletion_requests_consumer_no'))

    op.drop_table('menjin_deletion_requests')
    # ### end Alembic commands ###
