"""Add menjin privilege deletion request model

Revision ID: 7fbacf2776cd
Revises: b7250de94a33
Create Date: 2025-10-17 09:14:07.633139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbacf2776cd'
down_revision = 'b7250de94a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menjin_privilege_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=False),
    sa.Column('consumer_name', sa.String(length=64), nullable=False),
    sa.Column('door_id', sa.Integer(), nullable=False),
    sa.Column('door_name', sa.String(length=100), nullable=False),
    sa.Column('control_seg_id', sa.Integer(), nullable=False),
    sa.Column('control_seg_name', sa.String(length=100), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menjin_privilege_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menjin_privilege_deletion_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menjin_privilege_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menjin_privilege_deletion_requests_status'))

    op.drop_table('menjin_privilege_deletion_requests')
    # ### end Alembic commands ###
