"""Add pending systems table

Revision ID: 8cb06254020c
Revises: 7fbacf2776cd
Create Date: 2025-10-17 17:06:25.343706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb06254020c'
down_revision = '7fbacf2776cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=150), nullable=False),
    sa.Column('computer_name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_systems_computer_name'), ['computer_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_pending_systems_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_systems_status'))
        batch_op.drop_index(batch_op.f('ix_pending_systems_computer_name'))

    op.drop_table('pending_systems')
    # ### end Alembic commands ###
