"""Add is_active column to user links

Revision ID: b7250de94a33
Revises: de2ec86b769f
Create Date: 2025-10-14 10:38:47.149634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7250de94a33'
down_revision = 'de2ec86b769f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_system_user_link_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('workstation_user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_workstation_user_link_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_user_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workstation_user_link_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('system_user_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_user_link_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
