"""Add avamar_status column to system table

Revision ID: d7824f3c16bf
Revises: e3dfd35e7588
Create Date: 2025-11-05 13:50:21.340778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7824f3c16bf'
down_revision = 'e3dfd35e7588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_copy1', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_needs_qa_check'))
        batch_op.drop_index(batch_op.f('ix_system_system_number'))

    op.drop_table('system_copy1')
    with op.batch_alter_table('partial_disable_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_deletion_requests_status'))
        batch_op.create_index(batch_op.f('ix_partial_disable_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avamar_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('avamar_status')

    with op.batch_alter_table('partial_disable_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_disable_requests_status'))
        batch_op.create_index(batch_op.f('ix_partial_deletion_requests_status'), ['status'], unique=False)

    op.create_table('system_copy1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('system_number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('computer_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('is_domain_joined', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_workstation_domain_joined', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('warning_days', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_frequency_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_check_date', sa.DATE(), nullable=True),
    sa.Column('next_check_date', sa.DATE(), nullable=True),
    sa.Column('needs_qa_check', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('qa_last_check_date', sa.DATE(), nullable=True),
    sa.Column('qa_check_frequency_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qa_next_check_date', sa.DATE(), nullable=True),
    sa.Column('backup_method', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('backup_frequency', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('is_restore_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_restore_verification_date', sa.DATE(), nullable=True),
    sa.Column('restore_verification_cycle', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('it_check_content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('last_backup_date', sa.DATE(), nullable=True),
    sa.Column('next_backup_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('system_copy1_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_copy1', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_system_number'), ['system_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_needs_qa_check'), ['needs_qa_check'], unique=False)

    # ### end Alembic commands ###
