"""Add PartialDeletionRequest model

Revision ID: de2ec86b769f
Revises: 75783729cded
Create Date: 2025-10-13 16:34:40.805510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2ec86b769f'
down_revision = '75783729cded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partial_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('chinese_name', sa.String(length=64), nullable=False),
    sa.Column('system_user_links', sa.Text(), nullable=True),
    sa.Column('workstation_user_links', sa.Text(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partial_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_deletion_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partial_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_deletion_requests_status'))

    op.drop_table('partial_deletion_requests')
    # ### end Alembic commands ###
