"""Add backup date fields to System

Revision ID: e3dfd35e7588
Revises: 7266a451fc61
Create Date: 2025-10-24 13:10:36.582583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dfd35e7588'
down_revision = '7266a451fc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_backup_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_backup_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('next_backup_date')
        batch_op.drop_column('last_backup_date')

    # ### end Alembic commands ###
