"""Refactor deletion to disable functionality

Revision ID: e6532de87999
Revises: de2ec86b769f
Create Date: 2025-10-14 09:43:01.789771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6532de87999'
down_revision = 'de2ec86b769f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disable_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_to_disable_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_to_disable_id'], ['system_accounts.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partial_disable_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('chinese_name', sa.String(length=64), nullable=False),
    sa.Column('system_user_links', sa.Text(), nullable=True),
    sa.Column('workstation_user_links', sa.Text(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partial_disable_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_disable_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('partial_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_deletion_requests_status'))

    op.drop_table('partial_deletion_requests')
    op.drop_table('deletion_requests')
    with op.batch_alter_table('system_user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_system_user_link_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('workstation_user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_workstation_user_link_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_user_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workstation_user_link_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('system_user_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_user_link_is_active'))
        batch_op.drop_column('is_active')

    op.create_table('deletion_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_to_delete_id', sa.INTEGER(), nullable=False),
    sa.Column('requested_by_id', sa.INTEGER(), nullable=False),
    sa.Column('request_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_to_delete_id'], ['system_accounts.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partial_deletion_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('requested_by_id', sa.INTEGER(), nullable=False),
    sa.Column('chinese_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('system_user_links', sa.TEXT(), nullable=True),
    sa.Column('workstation_user_links', sa.TEXT(), nullable=True),
    sa.Column('request_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partial_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_deletion_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('partial_disable_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_disable_requests_status'))

    op.drop_table('partial_disable_requests')
    op.drop_table('disable_requests')
    # ### end Alembic commands ###
